# Generated by Django 4.2.30 on 2026-06-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0004_alter_solicitudmaterial_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudmaterial",
            name="ine_documento",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="ine_solicitudes/",
                verbose_name="Documento INE",
            ),
        ),
        migrations.AddField(
            model_name="solicitudmaterial",
            name="ine_rechazo_motivo",
            field=models.TextField(blank=True, verbose_name="Motivo de rechazo de INE"),
        ),
    ]
