# Generated by Django 4.2.30 on 2026-06-06 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("areas", "0001_initial"),
        ("procurement", "0005_solicitudmaterial_ine_documento_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="solicitudmaterial",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Solicitud de material",
                "verbose_name_plural": "Solicitudes de Material",
            },
        ),
        migrations.CreateModel(
            name="HistoricalSolicitudMaterial",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Número de solicitud"
                    ),
                ),
                (
                    "fecha_solicitud",
                    models.DateField(verbose_name="Fecha de solicitud"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción general"),
                ),
                (
                    "justificacion",
                    models.TextField(blank=True, verbose_name="Justificación"),
                ),
                (
                    "eje_rector",
                    models.TextField(
                        blank=True,
                        help_text="Ej: Bienestar Social, Ambiente Sano, etc.",
                        verbose_name="Eje Rector",
                    ),
                ),
                (
                    "programa_presupuestario",
                    models.TextField(
                        blank=True,
                        help_text="Ej: Apoyar y subsidiar con recursos económicos a grupos vulnerables",
                        verbose_name="Programa Presupuestario",
                    ),
                ),
                (
                    "actividad",
                    models.TextField(
                        blank=True,
                        help_text="Ej: Apoyar económicamente o en especie a solicitudes procedentes",
                        verbose_name="Actividad o Acción",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente_verificacion", "Pendiente de Verificación INE"),
                            ("ine_rechazada", "INE Rechazada"),
                            ("borrador", "Borrador"),
                            ("enviado", "Enviado"),
                            ("en_cotizacion", "En Cotización"),
                            ("cotizado", "Cotizado"),
                            ("en_autorizacion", "En Autorización"),
                            ("autorizado", "Autorizado"),
                            ("en_orden", "En Orden de Compra"),
                            ("parcial", "Parcialmente Entregado"),
                            ("entregado", "Entregado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="borrador",
                        max_length=30,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "total_estimado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Total estimado",
                    ),
                ),
                ("urgente", models.BooleanField(default=False, verbose_name="Urgente")),
                (
                    "fecha_requerida",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha requerida"
                    ),
                ),
                (
                    "ine_documento",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Documento INE",
                    ),
                ),
                (
                    "ine_rechazo_motivo",
                    models.TextField(
                        blank=True, verbose_name="Motivo de rechazo de INE"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        verbose_name="Fecha de actualización",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="areas.area",
                        verbose_name="Área solicitante",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Solicitud de material",
                "verbose_name_plural": "historical Solicitudes de Material",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
