# Generated by Django 4.2.30 on 2026-06-07 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0006_alter_solicitudmaterial_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="solicitudmaterial",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Solicitud de Material",
                "verbose_name_plural": "Solicitudes de Material",
            },
        ),
        migrations.DeleteModel(
            name="HistoricalSolicitudMaterial",
        ),
    ]
