# Generated by Django 4.2.30 on 2026-06-06 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0001_initial"),
        ("invoices", "0005_historicalfactura"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalEntregaBienes",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Número de recepción"
                    ),
                ),
                (
                    "fecha_recepcion",
                    models.DateTimeField(verbose_name="Fecha de recepción"),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "completa",
                    models.BooleanField(default=False, verbose_name="Entrega completa"),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="invoices.factura",
                        verbose_name="Factura",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="orders.ordencompra",
                        verbose_name="Orden de Compra",
                    ),
                ),
                (
                    "recibido_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recibido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Entrega de Bienes",
                "verbose_name_plural": "historical Entregas de Bienes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
