# Generated by Django 4.2.30 on 2026-06-07 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("areas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("procurement", "0007_alter_solicitudmaterial_options_and_more"),
        ("inventory", "0002_historicalentregabienes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Articulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código SKU"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del artículo"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "unidad_medida",
                    models.CharField(max_length=50, verbose_name="Unidad de medida"),
                ),
                (
                    "costo_promedio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Costo promedio",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articulos",
                        to="procurement.cog",
                        verbose_name="Partida COG",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artículo",
                "verbose_name_plural": "Artículos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Auditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(max_length=50, unique=True, verbose_name="Folio"),
                ),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "En Proceso"),
                            ("pendiente", "Pendiente de Autorización"),
                            ("cerrada", "Cerrada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "almacen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auditorias",
                        to="areas.area",
                        verbose_name="Almacén",
                    ),
                ),
                (
                    "autorizada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auditorias_autorizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auditorias_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoría",
                "verbose_name_plural": "Auditorías",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="AuditoriaDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "existencia_sistema",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                (
                    "existencia_fisica",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                (
                    "diferencia",
                    models.DecimalField(
                        decimal_places=4, help_text="fisica - sistema", max_digits=15
                    ),
                ),
                ("justificacion", models.TextField(blank=True)),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.articulo",
                    ),
                ),
                (
                    "auditoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="inventory.auditoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Auditoría",
                "verbose_name_plural": "Detalles de Auditoría",
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=15,
                        verbose_name="Existencia actual",
                    ),
                ),
                (
                    "cantidad_reservada",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=15,
                        verbose_name="Cantidad reservada",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "almacen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stocks",
                        to="areas.area",
                        verbose_name="Almacén",
                    ),
                ),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stocks",
                        to="inventory.articulo",
                        verbose_name="Artículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock",
                "verbose_name_plural": "Stocks",
                "unique_together": {("almacen", "articulo")},
            },
        ),
        migrations.RemoveField(
            model_name="salidadetalle",
            name="material",
        ),
        migrations.RemoveField(
            model_name="salidadetalle",
            name="unidad",
        ),
        migrations.DeleteModel(
            name="HistoricalEntregaBienes",
        ),
        migrations.AddField(
            model_name="entregadetalle",
            name="articulo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entregas",
                to="inventory.articulo",
                verbose_name="Artículo",
            ),
        ),
        migrations.AddField(
            model_name="salidadetalle",
            name="articulo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="salidas",
                to="inventory.articulo",
                verbose_name="Artículo",
            ),
        ),
    ]
