# Generated by Django 4.2.30 on 2026-06-07 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("areas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0003_articulo_auditoria_auditoriadetalle_stock_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AjusteInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(max_length=50, unique=True, verbose_name="Folio"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "motivo_general",
                    models.CharField(
                        choices=[
                            ("dano", "Daño"),
                            ("robo", "Robo"),
                            ("caducidad", "Caducidad"),
                            ("error", "Error de captura"),
                            ("perdida", "Pérdida"),
                            ("admin", "Ajuste administrativo"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=20,
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "evidencia",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="evidencias/ajustes/",
                        verbose_name="Evidencia",
                    ),
                ),
                (
                    "justificacion",
                    models.TextField(verbose_name="Justificación detallada"),
                ),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                ("fecha_autorizacion", models.DateTimeField(blank=True, null=True)),
                (
                    "almacen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ajustes",
                        to="areas.area",
                        verbose_name="Almacén",
                    ),
                ),
                (
                    "autorizador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ajustes_autorizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autorizador",
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ajustes_solicitados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ajuste de Inventario",
                "verbose_name_plural": "Ajustes de Inventario",
                "ordering": ["-fecha_solicitud"],
            },
        ),
        migrations.AddField(
            model_name="entregadetalle",
            name="fecha_caducidad",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Caducidad"
            ),
        ),
        migrations.AddField(
            model_name="entregadetalle",
            name="lote",
            field=models.CharField(blank=True, max_length=100, verbose_name="Lote"),
        ),
        migrations.AddField(
            model_name="entregadetalle",
            name="numero_serie",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Número de Serie"
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="estado_articulo",
            field=models.CharField(
                choices=[
                    ("disponible", "Disponible"),
                    ("danado", "Dañado"),
                    ("en_garantia", "En Garantía"),
                    ("baja", "Baja Definitiva"),
                ],
                default="disponible",
                max_length=20,
                verbose_name="Estado del artículo",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="fecha_caducidad_referencia",
            field=models.DateField(
                blank=True, null=True, verbose_name="Caducidad Referencia"
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="lote_referencia",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Lote Referencia"
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="numero_serie_referencia",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="No. Serie Referencia"
            ),
        ),
        migrations.CreateModel(
            name="DevolucionInterna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(max_length=50, unique=True, verbose_name="Folio"),
                ),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                ("fecha_recepcion", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("completada", "Completada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "almacen_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devoluciones_recibidas",
                        to="areas.area",
                        verbose_name="Almacén destino",
                    ),
                ),
                (
                    "area_origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devoluciones_enviadas",
                        to="areas.area",
                        verbose_name="Área origen",
                    ),
                ),
                (
                    "recibido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devoluciones_confirmadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recibido por",
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devoluciones_solicitadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devolución Interna",
                "verbose_name_plural": "Devoluciones Internas",
                "ordering": ["-fecha_solicitud"],
            },
        ),
        migrations.CreateModel(
            name="DevolucionDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.articulo",
                    ),
                ),
                (
                    "devolucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="inventory.devolucioninterna",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Devolución",
                "verbose_name_plural": "Detalles de Devolución",
            },
        ),
        migrations.CreateModel(
            name="AjusteInventarioDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("suma", "Suma"), ("resta", "Resta")],
                        max_length=10,
                        verbose_name="Tipo de ajuste",
                    ),
                ),
                (
                    "ajuste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="inventory.ajusteinventario",
                    ),
                ),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.articulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Ajuste",
                "verbose_name_plural": "Detalles de Ajuste",
            },
        ),
    ]
