# Generated by Django 4.2.30 on 2026-06-07 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_ajusteinventario_entregadetalle_fecha_caducidad_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ajusteinventario",
            name="evidencia",
        ),
        migrations.AddField(
            model_name="devolucioninterna",
            name="salida_origen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devoluciones",
                to="inventory.salidabienes",
                verbose_name="Salida origen",
            ),
        ),
        migrations.CreateModel(
            name="EvidenciaAjuste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        upload_to="evidencias/ajustes/", verbose_name="Imagen"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Descripción"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ajuste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidencias",
                        to="inventory.ajusteinventario",
                        verbose_name="Ajuste",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidencia de Ajuste",
                "verbose_name_plural": "Evidencias de Ajuste",
            },
        ),
    ]
