# Generated by Django 4.2.30 on 2026-06-06 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0005_alter_firmantedocumento_tipo_documento"),
        ("quotations", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudautorizacion",
            name="motivo_rechazo",
            field=models.TextField(blank=True, verbose_name="Motivo de rechazo"),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="autorizacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ordenes_compra",
                to="orders.autorizacionpresupuestal",
                verbose_name="Autorización",
            ),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="cotizacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ordenes_compra",
                to="quotations.cotizacionmaterial",
                verbose_name="Cotización",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalOrdenCompra",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Número"
                    ),
                ),
                ("fecha_emision", models.DateField(verbose_name="Fecha de emisión")),
                (
                    "fecha_entrega_esperada",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de entrega esperada"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "iva",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="IVA"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Total"
                    ),
                ),
                (
                    "condiciones_pago",
                    models.TextField(blank=True, verbose_name="Condiciones de pago"),
                ),
                (
                    "lugar_entrega",
                    models.TextField(blank=True, verbose_name="Lugar de entrega"),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("enviada", "Enviada"),
                            ("confirmada", "Confirmada por Proveedor"),
                            ("parcial", "Parcialmente Entregada"),
                            ("entregada", "Entregada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="borrador",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "referencia_externa",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Referencia externa"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "autorizacion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="orders.autorizacionpresupuestal",
                        verbose_name="Autorización",
                    ),
                ),
                (
                    "cotizacion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="quotations.cotizacionmaterial",
                        verbose_name="Cotización",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="companies.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Orden de Compra",
                "verbose_name_plural": "historical Órdenes de Compra",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
