# Generated by Django 4.2.30 on 2026-06-07 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_solicitudautorizacion_motivo_rechazo_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalOrdenCompra",
        ),
    ]
