# Generated by Django 4.2.30 on 2026-05-29 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('accounts', '0002_user_ine_foto_user_ine_rechazada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ine_foto',
        ),
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='areas.area', verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='user',
            name='ine_documento',
            field=models.FileField(blank=True, null=True, upload_to='ine/', verbose_name='Documento INE'),
        ),
        migrations.AddField(
            model_name='user',
            name='puesto',
            field=models.CharField(blank=True, max_length=100, verbose_name='Puesto'),
        ),
    ]
