# Generated by Django 4.2.30 on 2026-06-11 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_historicaluser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalUser",
        ),
    ]
