# Generated by Django 4.2.30 on 2026-06-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_company_membrete_company_pie_pagina_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firmantedocumento",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("solicitud", "Solicitud de Materiales"),
                    ("cotizacion", "Cotización"),
                    ("solicitud_autorizacion", "Solicitud de Autorización"),
                    ("autorizacion", "Autorización Presupuestal"),
                    ("orden_compra", "Orden de Compra"),
                    ("entrega", "Entrega/Recepción"),
                    ("salida", "Salida de Almacén"),
                    ("solicitud_gasto", "Solicitud del Gasto"),
                    ("solicitud_pago", "Solicitud de Pago"),
                    ("distribucion_gasto", "Distribución del Gasto"),
                ],
                max_length=30,
                verbose_name="Tipo de Documento",
            ),
        ),
    ]
