# Generated by Django 4.2.30 on 2026-06-06 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0005_alter_firmantedocumento_tipo_documento"),
        ("invoices", "0004_add_is_quick_flow"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalFactura",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "xml_file",
                    models.TextField(max_length=100, verbose_name="Archivo XML"),
                ),
                (
                    "pdf_file",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Archivo PDF",
                    ),
                ),
                (
                    "uuid_cfdi",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=36,
                        null=True,
                        verbose_name="UUID CFDI",
                    ),
                ),
                (
                    "folio",
                    models.CharField(blank=True, max_length=50, verbose_name="Folio"),
                ),
                (
                    "serie",
                    models.CharField(blank=True, max_length=25, verbose_name="Serie"),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de emisión"
                    ),
                ),
                (
                    "rfc_emisor",
                    models.CharField(
                        blank=True, max_length=13, verbose_name="RFC Emisor"
                    ),
                ),
                (
                    "nombre_emisor",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nombre Emisor"
                    ),
                ),
                (
                    "rfc_receptor",
                    models.CharField(
                        blank=True, max_length=13, verbose_name="RFC Receptor"
                    ),
                ),
                (
                    "nombre_receptor",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nombre Receptor"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Descuento",
                    ),
                ),
                (
                    "iva",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="IVA"
                    ),
                ),
                (
                    "isr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="ISR Retenido",
                    ),
                ),
                (
                    "iva_retenido",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="IVA Retenido",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Total"
                    ),
                ),
                (
                    "forma_pago",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Forma de pago"
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Método de pago"
                    ),
                ),
                (
                    "moneda",
                    models.CharField(
                        default="MXN", max_length=10, verbose_name="Moneda"
                    ),
                ),
                (
                    "tipo_cambio",
                    models.DecimalField(
                        decimal_places=4,
                        default=1,
                        max_digits=10,
                        verbose_name="Tipo de cambio",
                    ),
                ),
                (
                    "tipo_comprobante",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Tipo de comprobante"
                    ),
                ),
                (
                    "uso_cfdi",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Uso CFDI"
                    ),
                ),
                (
                    "parsed_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="JSON Parseado"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de procesar"),
                            ("procesando", "Procesando"),
                            ("procesada", "Procesada"),
                            ("error", "Error en procesamiento"),
                            ("distribuida", "Distribuida"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensaje de error"),
                ),
                (
                    "is_quick_flow",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si la factura fue procesada mediante el flujo rápido (sin solicitud/orden previa)",
                        verbose_name="Flujo rápido",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="companies.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Subido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Factura",
                "verbose_name_plural": "historical Facturas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
