# Generated by Django 4.2.30 on 2026-06-07 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0003_delete_historicalordencompra"),
        ("inventory", "0005_remove_ajusteinventario_evidencia_and_more"),
        ("invoices", "0005_historicalfactura"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacturaHistorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_anterior",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Estado Anterior"
                    ),
                ),
                (
                    "estado_nuevo",
                    models.CharField(max_length=20, verbose_name="Estado Nuevo"),
                ),
                (
                    "comentarios",
                    models.TextField(blank=True, verbose_name="Comentarios"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Historial de Factura",
                "verbose_name_plural": "Historiales de Factura",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="LotePago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_pago",
                    models.DateField(verbose_name="Fecha de pago programada"),
                ),
                (
                    "cuenta_origen",
                    models.CharField(max_length=50, verbose_name="Cuenta origen"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programado", "Programado"),
                            ("pagado", "Pagado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="programado",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lotes_pago_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote de Pago",
                "verbose_name_plural": "Lotes de Pago",
            },
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Monto Pagado"
                    ),
                ),
                ("fecha_pago", models.DateField(verbose_name="Fecha de Pago Real")),
                (
                    "comprobante",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="pagos/comprobantes/",
                        verbose_name="Comprobante de Pago (PDF/XML)",
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Referencia de Transacción",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos_registrados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
            },
        ),
        migrations.AddField(
            model_name="factura",
            name="orden_compra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facturas",
                to="orders.ordencompra",
                verbose_name="Orden de Compra",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="recepcion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facturas_asociadas",
                to="inventory.entregabienes",
                verbose_name="Recepción",
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente de procesar"),
                    ("procesando", "Procesando"),
                    ("procesada", "Procesada"),
                    ("validando", "En Validación"),
                    ("rechazada", "Rechazada"),
                    ("autorizada", "Autorizada CXP"),
                    ("programada", "Pago Programado"),
                    ("pagada", "Pagada"),
                    ("error", "Error en procesamiento"),
                    ("distribuida", "Distribuida (Legacy)"),
                ],
                default="pendiente",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.DeleteModel(
            name="HistoricalFactura",
        ),
        migrations.AddField(
            model_name="pago",
            name="factura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pagos",
                to="invoices.factura",
                verbose_name="Factura",
            ),
        ),
        migrations.AddField(
            model_name="pago",
            name="lote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pagos",
                to="invoices.lotepago",
                verbose_name="Lote",
            ),
        ),
        migrations.AddField(
            model_name="facturahistorial",
            name="factura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial",
                to="invoices.factura",
                verbose_name="Factura",
            ),
        ),
        migrations.AddField(
            model_name="facturahistorial",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eventos_factura",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
    ]
